version: '3.3'

services:
  # db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - /var/lib/postgresql/data/
  #   env_file:
  #     - ./.env

  web:
    build: ../backend/grocket/
    restart: always
    volumes:
      - data_value:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - redis
      # - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
    volumes:
      - react_build:/react/dist

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - react_build:/var/www/react
    depends_on:
      - frontend
      - web

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data

volumes:
  static_value:
  media_value:
  data_value:
  react_build:
  redis:
