# Generated by Django 3.2.18 on 2023-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_nl',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='category title'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_nl',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
