# Generated by Django 4.1.7 on 2023-03-30 16:29

from django.db import migrations
import products.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=products.fields.RichTextBleachField(max_length=1000, verbose_name='product description'),
        ),
    ]
