# Generated by Django 4.2 on 2023-04-13 12:47

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models

import products.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ("-id",),
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.AlterModelOptions(
            name="productaddress",
            options={
                "ordering": ("-id",),
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=50, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title_en",
            field=models.CharField(max_length=50, null=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title_nl",
            field=models.CharField(max_length=50, null=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title_ru",
            field=models.CharField(max_length=50, null=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="favourite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourites",
                to="products.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="image",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="is main"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=products.fields.RichTextBleachField(
                max_length=1000, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="USD",
                max_digits=19,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.promotion",
                verbose_name="promotion types",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="pub date"
            ),
        ),
        migrations.AlterField(
            model_name="productaddress",
            name="city",
            field=models.CharField(blank=True, max_length=150, verbose_name="city"),
        ),
    ]
