# Generated by Django 4.2 on 2023-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='stripe_id',
            field=models.CharField(default=None, max_length=50, verbose_name='stripe_id'),
        ),
    ]
