# Generated by Django 4.2 on 2023-04-14 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_image_options_alter_productaddress_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("title",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
