# Generated by Django 4.1.7 on 2023-03-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_title_af_remove_category_title_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.promotion', verbose_name='product promotion types'),
        ),
    ]
