# Generated by Django 4.2 on 2023-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripePromotionsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Pub date')),
                ('stripe_id', models.CharField(default=None, max_length=50, null=True, verbose_name='stripe_id')),
            ],
            options={
                'verbose_name': 'stripe promotions transaction',
                'verbose_name_plural': 'stripe promotions transaction',
                'ordering': ('-id',),
            },
        ),
    ]
