# Generated by Django 4.2 on 2023-05-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_promotion_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePromotionsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.product', verbose_name='product')),
                ('promotions', models.ManyToManyField(related_name='transaction', to='products.promotion', verbose_name='promotion types')),
            ],
            options={
                'verbose_name': 'stripe promotions transaction',
                'verbose_name_plural': 'stripe promotions transaction',
                'ordering': ('-id',),
            },
        ),
    ]
