# Generated by Django 4.2 on 2023-05-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepromotionstransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='stripepromotionstransaction',
            name='promotions',
            field=models.ManyToManyField(related_name='transaction', to='products.promotion', verbose_name='promotion types'),
        ),
    ]
