# Generated by Django 4.2 on 2023-08-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepromotionstransaction',
            name='stripe_id',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='stripe_id'),
        ),
    ]
