# Generated by Django 4.2 on 2023-05-14 15:28

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default=45, max_length=2),
            preserve_default=False,
        ),
    ]
