# Generated by Django 4.2 on 2023-05-14 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='text')),
                ('rate', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Pub date')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comments/')),
            ],
            options={
                'verbose_name': 'comment image',
                'verbose_name_plural': 'comment images',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_nl', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_sv', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_it', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_de', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_zh_hant', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_pl', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('name', models.SlugField(verbose_name='code')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='text')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Pub date')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='comments.comment', verbose_name='comment')),
            ],
            options={
                'verbose_name': 'comment reply',
                'verbose_name_plural': 'comment replies',
                'ordering': ('-pub_date',),
            },
        ),
    ]
