# Generated by Django 4.2 on 2023-08-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='title_zh_hant',
            new_name='title_zh_hans',
        ),
    ]
