# Generated by Django 4.2 on 2023-04-14 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_image_options_alter_productaddress_options_and_more"),
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="products.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True, max_length=500, verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="text",
            field=models.TextField(max_length=500, verbose_name="text"),
        ),
    ]
